### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by Natercia18** [sukiweb/CreandoUnChatbotEnPython#1]
Buenas noches,

Me ha encantado el vídeo publicado, la verdad es que está muy bien explicado pero tengo un problema y es que no entiendo bien cómo se ha creado la base de datos en MongoDB.

Cuando busco la collection me devuelve null porque no sé cómo insertar los valores o que me cree lo necesario para este trabajo.
¿El fichero hay que insertarlo en algún sitio o solamente recogerlo como lo tienes en el código?

Muchísimas gracias,
Un saludo

**Comment by sukiweb** [comment]
En este notebook no he tenido en cuenta la creación de base de datos y colecciones pertinentes. Simplemente lo comento en el vídeo (creo la base de datos desde cero, creo recordar), pero no está incluido en el Notebook, ya que no era el objetivo de la explicación del mismo.

Para crear una base de datos en MongoDB te recomiendo que revises la propia documentación de la base de datos, que viene con manuales paso a paso de cómo crearla.
